apiVersion: devops.alauda.io/v1alpha1
kind: ClusterPipelineTemplate
metadata:
  name: alaudaSyncImageTrigger
  annotations:
    displayName.zh-CN: 触发器同步镜像
    displayName.en: Trigger Sync Image
    description.zh-CN: 触发器同步镜像模板。触发器接收到源镜像仓库变更，就将一个镜像从源仓库同步到目标仓库。若源镜像或目标镜像仓库为私有仓库（内网地址），需确保 Jenkins 服务与其在同一网络环境内，方可使用。
    description.en: Trigger Sync image template. When trigger receive a alteration，then synchronize a Image tag from the source repository to the target repository. If the source image or target image repository is a private repository (intranet address), ensure that Jenkins services are available in the same network.
    version: "3.0.13"
    style.icon: docker
  labels:
    category: SyncImage
spec:
  engine: graph
  withSCM: false
  agent:
    label: tools
    labelMatcher: tools
  options:
    raw: "buildDiscarder(logRotator(numToKeepStr: '200'))"
  stages:
    - name: SyncImage
      tasks:
        - name: alaudaSyncImage
          kind: ClusterPipelineTaskTemplate
          type: public/alaudaSyncImage
  post:
    always:
      - name: notification
        kind: ClusterPipelineTaskTemplate
        relation:
          - action: show
            when:
              name: UseNotification
              value: true
  parameters:
    - name: imageTag
      type: StringParameterDefinition
      value: "latest"
      description: Image Tag
  arguments:
    - displayName:
        zh-CN: "源镜像信息"
        en: "Source Image Info"
      items:
        - name: "sourceImageRepository"
          schema:
            type: string
          binding:
            - alaudaSyncImage.args.sourceImageRepository
          display:
            type: imageRepositoryList
            name:
              zh-CN: "源镜像仓库地址"
              en: "Address of source Image repository"
            description:
              zh-CN: "选择镜像仓库。例：index.docker.io/alauda/hello-world"
              en: "When synchronizing the images, select the source images directly if the images are platform images. If the source images are third party images, you must enter the third party repository address, for example, alauda/hello-world"
          required: true
          value: ""
        - name: "syncSourceImageTag"
          schema:
            type: string
            enum:
              - "alterationTag"
              - "assignTag"
          binding:
            - alaudaSyncImage.args.syncSourceImageTag
          display:
            type: "radio"
            advanced: false
            name:
              zh-CN: "同步源镜像标签"
              en: "Sync Source Image Tag"
            enumAlias:
              - "同步变动标签"
              - "同步指定标签"
            description:
              zh-CN: "同步源镜像标签。例：同步变动标签"
              en: "Switch synchronized source image tag,for example \"sync alteration tag\"."
          required: true
          default: "alterationTag"
          value: "alterationTag"
        - name: "sourceImageTag"
          schema:
            type: string
          binding:
            - alaudaSyncImage.args.sourceImageTag
          display:
            type: string
            advanced: false
            name:
              zh-CN: "源镜像标签"
              en: "Source image tag"
            description:
              zh-CN: "源镜像的版本。例：latest"
              en: "When synchronizing the images, enter the version of the source image, for example, latest."
          required: true
          default: ${imageTag}
          value: ""
          relation:
            - action: show
              when:
                name: syncSourceImageTag
                value: "assignTag"
    - displayName:
        zh-CN: "目标镜像信息"
        en: "Target Image Info"
      items:
        - name: imageRepositoryMode
          schema:
            type: string
            enum:
              - "choice"
              - "input"
          binding:
            - alaudaSyncImage.args.imageRepositoryMode
          display:
            type: radio
            advanced: false
            name:
              zh-CN: "方式"
              en: "Source Image Mode"
            enumAlias:
              - "选择"
              - "输入"
            description:
              zh-CN: "镜像仓库地址输入方式。例：选择"
              en: "Target Image Repository Mode."
          required: true
          default: "choice"
          value: "选择"
        - name: "targetImageRepositoryList"
          schema:
            type: string
          binding:
            - alaudaSyncImage.args.targetImageRepositoryList
          display:
            type: imageRepositoryList
            name:
              zh-CN: "目标镜像仓库地址"
              en: "Address of target Image repository"
            description:
              zh-CN: "选择镜像仓库。例：index.docker.io/alauda/hello-world"
              en: "When synchronizing the images, select the target images directly if the images are platform images. If the target images are third party images, you must enter the third party repository address, for example, alauda/hello-world"
          required: true
          value: ""
          relation:
            - action: show
              when:
                name: imageRepositoryMode
                value: "choice"
        - name: "targetImageRepository"
          schema:
            type: string
          binding:
            - alaudaSyncImage.args.targetImageRepository
          display:
            type: string
            name:
              zh-CN: "目标镜像仓库地址"
              en: "Address of target Image repository"
            description:
              zh-CN: "选择镜像仓库。例：index.docker.io/alauda/hello-world"
              en: "When synchronizing the images, select the target images directly if the images are platform images. If the target images are third party images, you must enter the third party repository address, for example, alauda/hello-world"
          required: false
          value: ""
          relation:
            - action: show
              when:
                name: imageRepositoryMode
                value: "input"
        - name: "targetCredentialsId"
          schema:
            type: string
          binding:
            - alaudaSyncImage.args.targetCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            args:
              type: kubernetes.io/dockerconfigjson
            name:
              zh-CN: "目标镜像凭据"
              en: "Target Credentials"
            description:
              zh-CN: "推送镜像时，使用的凭据"
              en: "Target Credentials"
          required: false
          value: ""
          relation:
            - action: show
              when:
                name: imageRepositoryMode
                value: "input"
  supportedTriggers:
    - type: imageTrigger
      enable: true
      sourceImageRepository:
        - sourceImageRepository
      sourceImageTag: imageTag
    - type: cron
